import { ENV } from '../../config/env.config';
import { ChatMessage } from '../../entities/ollama.entity';
import { ollamaClient } from '../../config/ollama';

const OllamaModel = ENV.OLLAMA_MODEL;

/**
 * Dispatches assembled conversational messages arrays down to the local Ollama node container 
 * infrastructure for context-aware inference processing.
 */
export async function askLLM(chatMessages: ChatMessage[]): Promise<string> {
  console.log(`[Ollama Inference] Streaming structured prompt arrays using model definition: ${ENV.OLLAMA_MODEL}`);

  try {
    const startTime = Date.now();
    
    const response = await ollamaClient.chat({
      model: OllamaModel,
      messages: chatMessages,
      stream: false,
      options: {
        num_ctx: 2048,
        temperature: 0.2
      }
    });

    const duration = ((Date.now() - startTime) / 1000).toFixed(2);
    console.log(`[Ollama Telemetry] Core inference pass completed inside ${duration}s window frame.`);
    
    return response.message?.content || "No response generated by the model.";
     
  } catch (error) {
    console.error('[Ollama Inference Error] Fatal exception caught inside askLLM communication stream:', error);
    throw error;
  }
}
